apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knote
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/DanielRamirez1901/CD-Jenkins-Kubernetes.git'
    targetRevision: HEAD
    path: helm-project
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

