namespace: parcial3
knote:
  image:
    repository: ventana1901/knote
    tag: 3
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000
  mongoUrl: mongodb://mongo:27017/dev
mongo:
  image:
    repository: mongo
    tag: 3
  pvc:
    accessModes:
      - ReadWriteOnce
    storage: 256Mi
