apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: knote
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: knote
  ports:
    - port: {{ .Values.knote.service.port }}
      targetPort: {{ .Values.knote.service.targetPort }}
  type: {{ .Values.knote.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: knote
          image: {{ .Values.knote.image.repository }}:{{ .Values.knote.image.tag }}
          ports:
            - containerPort: {{ .Values.knote.service.targetPort }}
          env:
            - name: MONGO_URL
              value: {{ .Values.knote.mongoUrl }}
          imagePullPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.pvc.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0.2-focal
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
