---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  namespace: parcial3
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins/
